# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Gu EnHao
subtitle: 'Code'
description: '古恩豪 的个人博客，记录技术栈。'
keywords:
  - Hexo
  - Blog
  - Gu EnHao
author: Gu EnHao
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://liangqianxing.github.io
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'

mathjax:
  tags: none
  single_dollar: true
  cjk_width: false
  normal: false

pandoc:
  pandocPath: pandoc
  timeout: 20000
  args:
    - --mathjax

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

feed:
  type: atom
  path: atom.xml
  limit: 20

search:
  path: search.json
  field: post
  content: true

sitemap:
  path: sitemap.xml

robotstxt:
  useragent: "*"
  allow:
    - /
  sitemap: /sitemap.xml

theme_config:
  scheme: Mist
  darkmode: true
  lightdark:
    enable: true
    check_supports: true
  language_switcher: false
  index_with_subtitle: true
  minify: true
  preconnect: true
  lazyload: true
  quicklink:
    enable: true
    home: true
    archive: true
  menu:
    home: / || fa fa-home
    projects: /projects/ || fa fa-rocket
    archives: /archives/ || fa fa-archive
    tags: /tags/ || fa fa-tags
    about: /about/ || fa fa-user
  menu_settings:
    icons: true
  social:
    GitHub: https://github.com/liangqianxing || fab fa-github
    Email: mailto:Guenhao2005@163.com || fa fa-envelope
    # RSS: /atom.xml || fa fa-rss
  social_icons:
    enable: true
    icons_only: false
  avatar:
    # url: https://avatars.githubusercontent.com/u/120540446?v=4
    url: images/avatar.png
    rounded: true
  sidebar:
    position: left
    display: always
  footer:
    since: 2025
    icon:
      name: fa fa-heart
      animated: true
      color: '#f06292'
    powered: true
    custom_text: 'Built with Hexo + NexT'
  codeblock:
    copy_button:
      enable: true
  creative_commons:
    license: by-nc-sa
    post: true
  local_search:
    enable: true
    top_n_per_article: 3
    unescape: false
  custom_file_path:
    head: source/_data/head.njk
    bodyEnd: source/_data/body-end.njk
    style: source/_data/styles.styl
  math:
    every_page: false
    mathjax:
      enable: true
    katex:
      enable: false
  links_settings:
    icon: fa fa-link      # 侧边栏标题前的图标（可选）
    layout: block         # block | inline
  links:
    小黄鼠: https://liumengxuan04.github.io/
    陈驰水: https://blog.chencs.online/posts/
    石上三年: https://blog.sssn.tech/
